/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AlertBase: typeof import('./../components/Alert/AlertBase.vue')['default']
    AlertBody: typeof import('./../components/Alert/AlertBody.vue')['default']
    AlertClose: typeof import('./../components/Alert/AlertClose.vue')['default']
    AlertIcon: typeof import('./../components/Alert/AlertIcon.vue')['default']
  }
}
